### ISSUE TITLE
What exactly do you mean by external and interanal?

### ISSUE THREAD

**Issue by HwanheeKim813** [addb-swstarlab/Knob-Representation#10]
I understand that external and internal are performance indicators, but could you kindly elaborate on the difference between the two?

**Comment by dkdl012** [comment]
Hi. Thank you for your interest in our code.

The internal metric is the statistics of the RocksDB states while benchmarking is in progress, such as count of rocksdb.block.cache.hit, rocksdb.l0.hit, rocksdb.memtable.hit and rocksdb.bytes.written. The external metric is an evaluation indicator for RocksDB performance. We used four external metrics: latency, throughput, write amplification, and space amplification.

I hope you found my answer helpful.
