### ISSUE TITLE
ImportError with 'from benchmark import exec_benchmark'

### ISSUE THREAD

**Issue by HwanheeKim813** [addb-swstarlab/Knob-Representation#12]
I have been working on your project and encountered an ImportError when trying to import the exec_benchmark function from the benchmark module.

I've searched for the corresponding installation package, but unfortunately, I was not able to find it in the project's documentation or in the usual package repositories.
Could you kindly assist in clarifying how I might be able to resolve this? Specifically, if there are any additional packages that need to be installed, could you please guide me on how to do so, or update the documentation to include this information?

Thank you for your time and assistance in this matter.

**Comment by dkdl012** [comment]
Hi, thanks for your interest in my project!

The "exec_benchmark" function and "benchmark" library are made by me. The function is just for connecting other server where RocksDB is installed and executing the RocksDB benchmarking, db_bench.
https://github.com/addb-swstarlab/Knob-Representation/blob/ef7bb6718d01f754856e9d80cd2d861e346bdbdd/main.py#L12 https://github.com/addb-swstarlab/Knob-Representation/blob/ef7bb6718d01f754856e9d80cd2d861e346bdbdd/main.py#L176

Therefore, you can write your own code to execute benchmarking commands generated on previous step. "recommend_command" indicates the command to execute db_bench including an optimal configuration.
https://github.com/addb-swstarlab/Knob-Representation/blob/ef7bb6718d01f754856e9d80cd2d861e346bdbdd/main.py#L170

I hope you find this answer helpful.
If you have nay questions, please let me know.

**Comment by HwanheeKim813** [comment]
I appreciate your help in addressing this issue. Thank you for providing assistance.
