### ISSUE TITLE
Inquiry about RocksDB Version Compatibility

### ISSUE THREAD

**Issue by HwanheeKim813** [addb-swstarlab/Knob-Representation#14]
Hello,

I am currently considering using your project and wanted to clarify if there are any specific version dependencies that I should be aware of. Could you please provide details on which version(s) of RocksDB are recommended or required for compatibility purposes?

Thank you for your assistance.

**Comment by dkdl012** [comment]
We used v6.25.0 for the RocksDB version.

RocksDB versions do not impact on the entire source code. You can use any version of RocksDB, however note that knobs to tune should be modified according to the changed version. 

If you need any further questions, please don't hesitate to ask me.

**Comment by HwanheeKim813** [comment]
Hello,

Thank you very much for the information and your prompt response. It's greatly appreciated!
