### ISSUE TITLE
About optimization algorithm.

### ISSUE THREAD

**Issue by Kwon-sein** [addb-swstarlab/Knob-Representation#2]
Hello, 

Do you have any special reason to use the Genetic Algorithm optimization method in Knob-Representation/models/steps.py/ ?

Was the optimization method with the best performance GA?

Thanks for reading.

**Comment by dkdl012** [comment]
Of course, other optimization algorithms can be used, too.
The reason that I have chosen the GA is, I think, that the GA has better complexity to recommend configurations than BO or others.

Thanks for asking.
