### ISSUE TITLE
Can you upload the data?

### ISSUE THREAD

**Issue by whduddhks** [addb-swstarlab/Knob-Representation#3]
Hi,
Thank you for providing the code.

I wonder there are some data to run the model.
In data folder, there are just name of the data files in readme.

Could you upload the data file that I can run the model?

Thank you.

**Comment by dkdl012** [comment]
Thanks for being interested in our work.

Unfortunately, we can not provide our data because the data are strongly dependent on hardware specs.
We recommend generating samples for yourself. The generating code is available on our repositories, RocksDB-data-generation. 

Thanks for asking!
