### ISSUE TITLE
About  model network.

### ISSUE THREAD

**Issue by Hyunjining** [addb-swstarlab/Knob-Representation#5]
Hello,

I read in Knob-Representation/models/network.py/ that input_dim has a greater value than hidden_dim.

I know it's good to specify the number of units in the hidden layer as a multiple of the number of input units.

Is there any special reason that input_dim is greater than hidden_dim?

Thanks for reading.

**Comment by dkdl012** [comment]
Hello, thanks for interesting on my works!

I can't know where the class you mentioned input_dim and hidden_dim, but I think it's probably class SingleNet.

The number of units in the hidden layer is commonly chosen dependent on a purpose of certain neural networks.
In this case, we want to predict smaller size of outputs from bigger size of inputs.

I hope my answer is helpful on your question.
