### ISSUE TITLE
About Workload Mapping

### ISSUE THREAD

**Issue by Kwon-sein** [addb-swstarlab/Knob-Representation#7]
Hi, 

Thanks for the interesting code.

When mapping workloads, I think it might be difficult to map all 16 workloads. 
Was the actual performance always good?

Thank you for reading!

**Comment by dkdl012** [comment]
It is not as hard as you thought.

The process of mapping workloads is to calculate the euclidean distance between target workloads and every 16 workloads.

The actual performance was good!

Thanks for your interest.
