### ISSUE TITLE
Questions about the code

### ISSUE THREAD

**Issue by SkiddieAhn** [addb-swstarlab/Knob-Representation#9]
When I checked the Attention Class on Knob-Representation/models/network.py , I checked the code for Bahdanau Attention. Was this attention more effective than general attention?

**Comment by dkdl012** [comment]
The attention module that we adopted was more effective for our model than others. However, this does not mean that the chosen module is always effective on other tasks.

There are lots kinds of attention modules, such as "additive attention" (known as Bahdanau Attention) and  "multiplicative attention" (known as Luong Attention). 

You can choose appropriate attention modules to fit your task or model.
